builds:
  - id: go-jira-migrate
    main: main.go
    binary: go-jira-migrate
    goos: [windows, darwin, linux, freebsd, openbsd]
    goarch: [amd64, arm, arm64]
    goarm: ["6", "7"]
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
archives:
  - id: go-jira-migrate
    builds: [go-jira-migrate]
    format: tar.gz
    files:
      - README.md
      - LICENSE
dist: target/dist
release:
  github:
    owner: natenho
    name: go-jira-migrate
  prerelease: auto
  disable: false
