name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install Dependencies
        run: go mod download

      - name: Build for Windows
        run: GOOS=windows go build -o go-jira-migrate.exe .

      - name: Build for Linux
        run: GOOS=linux go build -o go-jira-migrate .

      - name: Tag Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.tag_release.outputs.tag }}
          name: Release ${{ steps.tag_release.outputs.tag }}
          body: ${{ steps.tag_release.outputs.changelog }}
          
      - name: Upload Windows Binary
        uses: actions/upload-artifact@v3
        with:
          name: go-jira-migrate-windows-amd64
          path: go-jira-migrate.exe

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v3
        with:
          name: go-jira-migrate-linux-amd64
          path: go-jira-migrate
