name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install Dependencies
        run: go mod download

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o go-jira-migrate_windows_amd64.exe .
      
      - name: Build for Windows ARM
        run: GOOS=windows GOARCH=amd64 go build -o go-jira-migrate_windows_arm64.exe .

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o go-jira-migrate_linux_amd64 .

      - name: Build for Linux ARM
        run: GOOS=linux GOARCH=amd64 go build -o go-jira-migrate_linux_arm64 .

      - name: Build for OS X
        run: GOOS=darwin GOARCH=amd64 go build -o go-jira-migrate_darwin_amd64 .
        
      - name: Build for OS X ARM
        run: GOOS=darwin GOARCH=arm64 go build -o go-jira-migrate_darwin_arm64 .
        
      - name: Tag Release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.tag_release.outputs.new_tag }}
          name: ${{ steps.tag_release.outputs.new_tag }}
          body: ${{ steps.tag_release.outputs.changelog }}
          artifacts: go-jira-migrate*
